// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDVfhY_6xU2RxoY1xobO7NJIbZruB1Nis',
    appId: '1:125467062223:web:2584b1be66d94e2d4c2cba',
    messagingSenderId: '125467062223',
    projectId: 'cloud-messaging-giadagiacobbe',
    authDomain: 'cloud-messaging-giadagiacobbe.firebaseapp.com',
    storageBucket: 'cloud-messaging-giadagiacobbe.firebasestorage.app',
    measurementId: 'G-3VKPXX9BKR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJOl5lGWpTZ5MXU8L6EZtPCskgnDvhy1E',
    appId: '1:125467062223:android:85ac544f1682d0dc4c2cba',
    messagingSenderId: '125467062223',
    projectId: 'cloud-messaging-giadagiacobbe',
    storageBucket: 'cloud-messaging-giadagiacobbe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDo8Sgs3LdzxCbTna-e6wAhIy8PofH1zdA',
    appId: '1:125467062223:ios:ca2f3b46a884406f4c2cba',
    messagingSenderId: '125467062223',
    projectId: 'cloud-messaging-giadagiacobbe',
    storageBucket: 'cloud-messaging-giadagiacobbe.firebasestorage.app',
    iosBundleId: 'com.example.inclass17',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDo8Sgs3LdzxCbTna-e6wAhIy8PofH1zdA',
    appId: '1:125467062223:ios:ca2f3b46a884406f4c2cba',
    messagingSenderId: '125467062223',
    projectId: 'cloud-messaging-giadagiacobbe',
    storageBucket: 'cloud-messaging-giadagiacobbe.firebasestorage.app',
    iosBundleId: 'com.example.inclass17',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBDVfhY_6xU2RxoY1xobO7NJIbZruB1Nis',
    appId: '1:125467062223:web:7c8f2f07bba5392e4c2cba',
    messagingSenderId: '125467062223',
    projectId: 'cloud-messaging-giadagiacobbe',
    authDomain: 'cloud-messaging-giadagiacobbe.firebaseapp.com',
    storageBucket: 'cloud-messaging-giadagiacobbe.firebasestorage.app',
    measurementId: 'G-Y87T9KFLY6',
  );
}
